/**
 * In-app changelog string.
 *
 * This file is generated from CHANGELOG.md by:
 *   node scripts/sync-changelog.mjs
 *
 * Run that script (or `npm run sync-changelog`) before committing changes to
 * CHANGELOG.md so the in-app About screen stays up to date.
 *
 * DO NOT edit this file by hand — edit CHANGELOG.md instead.
 */

export type ChangelogSection = { title: string; items: string[] };

export type ChangelogEntry = {
  version: string;
  date: string | null;
  sections: ChangelogSection[];
  emptyNote?: string;
};

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
    {
      "version": "Unreleased",
      "date": null,
      "sections": [],
      "emptyNote": "No unreleased changes yet."
    },
    {
      "version": "0.9.0",
      "date": "2026-05-12",
      "sections": [
        {
          "title": "Added",
          "items": [
            "Native iOS/Android chat client for **OpenClaw** over WebSocket (`wss://`), with JSON-RPC request/response/events, keepalive/ticks, and defensive parsing of gateway payloads.",
            "**Device pairing** via Ed25519 identity keys stored only in Secure Store; challenge-response handshake before connecting.",
            "**Reconnection** with exponential backoff, jitter, capped attempts, and reconnect when the app returns to the foreground.",
            "**Session stream isolation** so switching sessions during streaming does not corrupt the UI; active-stream guards for chat events.",
            "Optional **SPKI certificate pinning** via the `expo-pinned-websocket` native module on iOS and Android; pin discovery (TOFU), pin mismatch handling, and Settings UI to manage pinned gateway keys.",
            "**Streaming assistant replies** with expandable thinking/reasoning blocks and tool-call cards (pending, running, completed, error).",
            "**Safe markdown** rendering for assistant content (no raw HTML injection).",
            "**Session management**: list, create, switch, and reset sessions; slide-out session sidebar with previews.",
            "**Agents** and **models** pickers wired to gateway catalogs.",
            "**Slash command palette** (`/`) with server-driven suggestions and **command confirmations** where the gateway requires them.",
            "**Multiple server profiles**: labeled gateways, per-profile gateway tokens in Secure Store only (never plaintext in AsyncStorage).",
            "**Connection status** and banners (connecting, pairing required, identity rejected, errors).",
            "**Settings**: server block (add/edit/remove profiles, logs), appearance (theme mode and dark variants), media-related options, **text-to-speech** controls (auto-speak replies, device vs gateway voice preferences), **About** screen with in-app changelog.",
            "**Onboarding** flow when no server profile exists yet.",
            "Optional **ClawBoy cloud identity** (Supabase): Sign in with Apple, Google (OAuth), and **email magic link**; account row in Settings is optional and does not block local-only gateway use; Supabase session tokens stored in Secure Store.",
            "**Feedback** submission to a configurable proxy endpoint; optional attachment of **recent screenshots** with privacy-conscious client preparation and a **Cloudflare Worker** companion for ingestion (see `infra/feedback-worker/`).",
            "**Encrypted on-disk chat cache** (AES-GCM) for faster cold-start UX; encryption key in Secure Store.",
            "**OTA updates** integration (`expo-updates`) with critical-update modal when applicable.",
            "**Infrastructure as code** for optional Supabase schema and Edge Functions under `infra/supabase/` (accounts, entitlements placeholder, account-delete, founders-related schema, **`purchases-webhook`** for store events), timestamped migrations, and local `supabase/config.toml` for CLI workflows — documented in `infra/supabase/README.md`.",
            "**Unit tests** (Jest) for protocol/helpers and key UI components; test configuration and mocks aligned with Expo/React Native.",
            "**Internationalization** (`i18n`): English and Simplified Chinese (`zh-CN`) string catalogs with a `LanguageProvider` and wired copy across onboarding, chat, input, settings, and common UI.",
            "**Demo mode**: local scripted OpenClaw client, demo storage, in-chat demo banner, and onboarding path to try the UI without a live gateway.",
            "**In-app purchases** (RevenueCat via `react-native-purchases`): `PurchasesContext`, product helpers, and Settings sections for **Founders** support and an optional **tip jar**; Founders badge for eligible accounts.",
            "**`serverPointers`** helper and related Supabase types for optional cloud-assisted server profile hints.",
            "**`ServerProfileSyncContext`**: optional sync path for server profile metadata with Supabase (plus unit tests for pointer resolution).",
            "**Account settings** screen and richer **Account** section (sign-in, account management) alongside existing Supabase auth flows.",
            "**Settings pairing card** for device pairing status and actions; **audio playing pill** in chat for inline playback/TTS affordance.",
            "**Hooks/utilities**: `useThrottledValue` for UI that should not update every frame; onboarding snapshot tests.",
            "**Badges / achievements system** (`src/badges/`): event-driven engine, unlock tracker, persistent store, tier definitions with color tokens, and `BadgesProvider`. Components: `BadgeCard`, `BadgeGrid`, `BadgePip`, `BadgeTierSegments`, `TrophyShelfScreen`, `UnlockToast`, `FoundersCountdown`, and `ProgressBar`.",
            "**Chat annotations**: `AnnotationContext`, `AnnotatedMessageBody`, `AnnotationsPill`, `InlineAnnotationRow`, `AnnotationPreviewModal`, and `AnnotationLayoutContext` — display and interact with inline source references attached to assistant replies.",
            "**Interactive options card** (`InteractiveOptionsCard`): renders gateway-driven choice buttons mid-conversation; full test coverage and protocol lib (`src/lib/openclaw/interactive.ts`).",
            "**Agent files viewer** (`AgentFileViewerModal`, `useAgentFiles`): browse and view files surfaced by the active agent during a session.",
            "**Streaming cursor** (`StreamingCursor`, `useStreamReveal`): animated blinking cursor that follows the live streaming edge of assistant text.",
            "**Section range picker** (`SectionRangePickerModal`): lets users select a line range within a file for targeted context attachment.",
            "**Conventions** (`ConventionInstallContext`, `src/lib/openclaw/installConventions.ts`, `SettingsConventionsSection`): install and manage project-level convention files from within the app.",
            "**Settings sub-screens** (`SettingsSubScreen`, `SettingsLinkRow`): reusable sub-screen wrapper + navigable link rows used by the new settings pages.",
            "**Settings split into file-based routes** (`app/settings/`): dedicated screens for About, Account, Achievements, Appearance, Conventions, Gateway Logs, Media, Pinned Keys, and Voice — each a focused page linked from the root Settings screen.",
            "**Brand components** (`BrandField`, `BrandLoader`, `BrandLogo`): shared branded UI primitives used in onboarding and settings.",
            "**Onboarding additions**: `AchievementsOptInStep` (opt-in to achievement tracking) and `AgentsMdPreviewModal` (preview an agent's AGENTS.md before connecting).",
            "**Message block parsing** (`src/lib/messageBlocks.ts`, `src/lib/messageMerge.ts`, `src/lib/openclaw/clientContext.ts`): structured decomposition of streamed assistant output into typed blocks for rendering.",
            "**`useInputTextController`**: dedicated hook managing draft text, cursor position, slash-command trigger detection, and paste handling; extracted from `InputBar`.",
            "**`useTokens`**: hook for tracking estimated token usage per session.",
            "**Debug ingest** (`src/lib/debugIngest.ts`): dev-only helper for ingesting and replaying raw gateway event logs.",
            "**Feedback dev bypass token** (`src/lib/feedback/devBypassToken.ts`): dev-mode token override for feedback submission without a live cloud account.",
            "**`useStreamReveal`**: hook that produces a progressively revealed string for streaming-text entry animations.",
            "**Utility modules** (`src/utils/links.ts`, `src/utils/markdownCache.ts`): safe URL helper and a keyed cache for parsed markdown ASTs to avoid redundant re-parses.",
            "**New test mocks**: `expo-network`, `file-viewer-context`, `reanimated-swipeable`, `use-agent-files`, `use-agents`.",
            "**New test coverage**: `InteractiveOptionsCard`, `StreamingTextRule`, `InputBarCard`, `useInputTextController`, `annotations`, `clientContext`, `installConventions`, `interactive`, `messageBlocks`, `messageMerge`, `messageParsing`, `links`, `demoIntegration`.",
            "**Feedback worker** (`infra/feedback-worker`): large expansion of the Cloudflare Worker — enriched ingestion pipeline, structured logging, and updated README.",
            "**Interactive options protocol doc** (`docs/interactive-options.md`): spec for gateway-driven interactive choice messages."
          ]
        },
        {
          "title": "Changed",
          "items": [
            "Iterative refactors of the OpenClaw WebSocket **client** and **chat** modules for clearer stream handling, typed events, reconnect behavior, and alignment with gateway semantics.",
            "**UI polish** across chat (headers, banners, bubbles, lists), onboarding, settings (including server block and meta panels), and theme tokens for consistency with the intended design system.",
            "**Pairing-required** messaging moved out of a dedicated chat surface into **Settings** (`PairingRequiredCard` removed from chat in favor of a settings pairing card).",
            "**Message list / bubbles**, **slash command palette**, **tool and thinking** cards, **connection banners**, and **input bar** pieces updated for demo mode, i18n, media/audio cues, and layout consistency.",
            "**Jest** split into **logic** vs **components** projects with shared setup tweaks for faster, clearer test runs.",
            "**`useServerConfig`** and related settings flows expanded for multi-profile editing, sync, and server-row UX; **`infra/supabase/README`** updated for the new migrations and functions.",
            "`app/settings.tsx` removed; settings navigation now handled by `app/settings/_layout.tsx` and per-screen files under `app/settings/`.",
            "`MessageBubble` and `MessageList` heavily refactored to render annotation rows, streaming cursor, agent-file viewer trigger, and interactive option cards inline.",
            "`InputBar` extracted input text state into `useInputTextController`; action bar, card, header, info row, and rainbow glow cleaned up and aligned with new hook.",
            "`OnboardingScreen` extended with achievements opt-in step and agents-md preview modal.",
            "`AboutScreen` and `SettingsMetaPanels` updated to reflect new settings structure and badge/account sections.",
            "`SessionRow` and `sessionSidebarStyles` refreshed for badge pip display and visual consistency.",
            "`ThemeContext` and `theme.ts` extended with badge tier color tokens and brand-color palette additions.",
            "`useChat` updated for block-based streaming; `useChatDiskHydration` and chat cache types extended to persist block structure.",
            "`useConnection` and `useAutoReconnect` hardened with cleaner generation tracking and backoff edge cases.",
            "`useDraft` rewritten to delegate text state to `useInputTextController`.",
            "`DemoOpenClawClient` updated to emit interactive option events and block-structured messages.",
            "`i18n` (EN + zh-CN) expanded with strings for badges, achievements, annotations, interactive options, conventions, agent files, and new settings screens.",
            "`jest.config.js` updated to include new test suites and mock registrations.",
            "**Inline reply card** redesigned: single-Q now has a header bar (question prompt or \"Reply\" fallback), Clear is always visible in the footer (disabled until dirty), Send button matches the main chat input (rounded square, ↑ arrow). Multi-Q dots grouped beside Skip to make pagination context clear; active/answered dots use accent color. `SegmentedIconPill` active segment now fills with accent color (applies to Install Mode, Theme Mode, and UI Density selectors).",
            "**Inline reply primer** (convention v5) compacted ~35%, opens with the explicit framing that interactive cards are the primary way to ask the user questions in ClawBoy.",
            "**App icon** refreshed to `icon-grid` with 3D depth treatment (shine, vignette, gradient-filled glyph, deep drop shadow from `icon-purple-large`); constellation updated to NW + S middle + SE (was NW + W middle + SE).",
            "**Splash screen** now uses a transparent-background variant of the same icon (`icon-grid-transparent.svg`) so the grid and glyph composite cleanly over the dark splash `backgroundColor` (`#080B12`) without any gradient edge clash.",
            "**Accessibility and localization** pass across chat, settings, onboarding, and shared UI: clearer `accessibilityLabel` / role coverage, focus order fixes, and i18n string gaps closed (pre-release audit X6).",
            "**Voice / TTS**: shared preferences context, audio-session cleanup, and gateway vs device voice heuristics by model; follow-up fixes from voice code review.",
            "**Onboarding** refactored into `app/onboarding/steps/*` and `components/*` modules (smaller surfaces, same flow).",
            "**Slash command palette** split into `components/input/palette/*` with hooks extracted for maintainability.",
            "**Session sidebar**: loading skeleton and error fallback for session list fetch failures.",
            "**Feedback sheet** split into smaller components and helpers; feedback worker gains Vitest coverage and dependency updates.",
            "**Repo hygiene (OSS prep)**: reference prototype removed from tracking, audit-driven cleanup of hygiene items (X1)."
          ]
        },
        {
          "title": "Fixed",
          "items": [
            "**Apple Sign-In button localization** — declared `CFBundleLocalizations: [en, zh-Hans]` in `Info.plist` so iOS resolves the app's effective UI language correctly. On Simplified Chinese devices the native `ASAuthorizationAppleIDButton` now renders \"通过 Apple 登录\" instead of the English fallback. Side effect: system permission prompts, `Alert` default buttons, the share sheet, and other native iOS surfaces also now render in the device language for supported locales.",
            "**Pinned WebSocket** native module (iOS/Android) follow-ups from native-config audit.",
            "**Annotations, badges, chat, and common components**: wave-2 / wave-3 audit remediations (correctness, tests, smaller UI fixes).",
            "**Supabase**: `fix_purchased_at` migration for purchase timestamp backfill.",
            "**Performance and dependencies**: targeted re-render / memo fixes and license-metadata follow-ups (X3 / X4 audits)."
          ]
        },
        {
          "title": "Security",
          "items": [
            "Gateway tokens, device identity material, Supabase session tokens when used, and chat-cache keys stored via **`expo-secure-store`** rather than AsyncStorage; RLS-oriented Supabase schema documented for cloud tables.",
            "Certificate pinning and explicit flows when a gateway certificate no longer matches a stored pin.",
            "**WebSocket ingress**: JSON text frames validated with **Zod** before dispatch to protocol handlers; stricter parsing of **auth callback** deep links (X2 security audit)."
          ]
        }
      ]
    }
  ];

export const CHANGELOG = `# Changelog

All notable changes to ClawBoy will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

---

## [Unreleased]

_No unreleased changes yet._

---

## [0.9.0] - 2026-05-12

First public release of ClawBoy. Initial App Store launch. Versioned **0.9.0** to signal pre-1.0 maturity; **1.0.0** will mark in-app purchase availability. Everything on the default branch through this entry is **v0.9.0** — there is not a separate in-tree “post-0.9” release line ahead of that tag.

### Added

- Native iOS/Android chat client for **OpenClaw** over WebSocket (\`wss://\`), with JSON-RPC request/response/events, keepalive/ticks, and defensive parsing of gateway payloads.
- **Device pairing** via Ed25519 identity keys stored only in Secure Store; challenge-response handshake before connecting.
- **Reconnection** with exponential backoff, jitter, capped attempts, and reconnect when the app returns to the foreground.
- **Session stream isolation** so switching sessions during streaming does not corrupt the UI; active-stream guards for chat events.
- Optional **SPKI certificate pinning** via the \`expo-pinned-websocket\` native module on iOS and Android; pin discovery (TOFU), pin mismatch handling, and Settings UI to manage pinned gateway keys.
- **Streaming assistant replies** with expandable thinking/reasoning blocks and tool-call cards (pending, running, completed, error).
- **Safe markdown** rendering for assistant content (no raw HTML injection).
- **Session management**: list, create, switch, and reset sessions; slide-out session sidebar with previews.
- **Agents** and **models** pickers wired to gateway catalogs.
- **Slash command palette** (\`/\`) with server-driven suggestions and **command confirmations** where the gateway requires them.
- **Multiple server profiles**: labeled gateways, per-profile gateway tokens in Secure Store only (never plaintext in AsyncStorage).
- **Connection status** and banners (connecting, pairing required, identity rejected, errors).
- **Settings**: server block (add/edit/remove profiles, logs), appearance (theme mode and dark variants), media-related options, **text-to-speech** controls (auto-speak replies, device vs gateway voice preferences), **About** screen with in-app changelog.
- **Onboarding** flow when no server profile exists yet.
- Optional **ClawBoy cloud identity** (Supabase): Sign in with Apple, Google (OAuth), and **email magic link**; account row in Settings is optional and does not block local-only gateway use; Supabase session tokens stored in Secure Store.
- **Feedback** submission to a configurable proxy endpoint; optional attachment of **recent screenshots** with privacy-conscious client preparation and a **Cloudflare Worker** companion for ingestion (see \`infra/feedback-worker/\`).
- **Encrypted on-disk chat cache** (AES-GCM) for faster cold-start UX; encryption key in Secure Store.
- **OTA updates** integration (\`expo-updates\`) with critical-update modal when applicable.
- **Infrastructure as code** for optional Supabase schema and Edge Functions under \`infra/supabase/\` (accounts, entitlements placeholder, account-delete, founders-related schema, **\`purchases-webhook\`** for store events), timestamped migrations, and local \`supabase/config.toml\` for CLI workflows — documented in \`infra/supabase/README.md\`.
- **Unit tests** (Jest) for protocol/helpers and key UI components; test configuration and mocks aligned with Expo/React Native.
- **Internationalization** (\`i18n\`): English and Simplified Chinese (\`zh-CN\`) string catalogs with a \`LanguageProvider\` and wired copy across onboarding, chat, input, settings, and common UI.
- **Demo mode**: local scripted OpenClaw client, demo storage, in-chat demo banner, and onboarding path to try the UI without a live gateway.
- **In-app purchases** (RevenueCat via \`react-native-purchases\`): \`PurchasesContext\`, product helpers, and Settings sections for **Founders** support and an optional **tip jar**; Founders badge for eligible accounts.
- **\`serverPointers\`** helper and related Supabase types for optional cloud-assisted server profile hints.
- **\`ServerProfileSyncContext\`**: optional sync path for server profile metadata with Supabase (plus unit tests for pointer resolution).
- **Account settings** screen and richer **Account** section (sign-in, account management) alongside existing Supabase auth flows.
- **Settings pairing card** for device pairing status and actions; **audio playing pill** in chat for inline playback/TTS affordance.
- **Hooks/utilities**: \`useThrottledValue\` for UI that should not update every frame; onboarding snapshot tests.
- **Badges / achievements system** (\`src/badges/\`): event-driven engine, unlock tracker, persistent store, tier definitions with color tokens, and \`BadgesProvider\`. Components: \`BadgeCard\`, \`BadgeGrid\`, \`BadgePip\`, \`BadgeTierSegments\`, \`TrophyShelfScreen\`, \`UnlockToast\`, \`FoundersCountdown\`, and \`ProgressBar\`.
- **Chat annotations**: \`AnnotationContext\`, \`AnnotatedMessageBody\`, \`AnnotationsPill\`, \`InlineAnnotationRow\`, \`AnnotationPreviewModal\`, and \`AnnotationLayoutContext\` — display and interact with inline source references attached to assistant replies.
- **Interactive options card** (\`InteractiveOptionsCard\`): renders gateway-driven choice buttons mid-conversation; full test coverage and protocol lib (\`src/lib/openclaw/interactive.ts\`).
- **Agent files viewer** (\`AgentFileViewerModal\`, \`useAgentFiles\`): browse and view files surfaced by the active agent during a session.
- **Streaming cursor** (\`StreamingCursor\`, \`useStreamReveal\`): animated blinking cursor that follows the live streaming edge of assistant text.
- **Section range picker** (\`SectionRangePickerModal\`): lets users select a line range within a file for targeted context attachment.
- **Conventions** (\`ConventionInstallContext\`, \`src/lib/openclaw/installConventions.ts\`, \`SettingsConventionsSection\`): install and manage project-level convention files from within the app.
- **Settings sub-screens** (\`SettingsSubScreen\`, \`SettingsLinkRow\`): reusable sub-screen wrapper + navigable link rows used by the new settings pages.
- **Settings split into file-based routes** (\`app/settings/\`): dedicated screens for About, Account, Achievements, Appearance, Conventions, Gateway Logs, Media, Pinned Keys, and Voice — each a focused page linked from the root Settings screen.
- **Brand components** (\`BrandField\`, \`BrandLoader\`, \`BrandLogo\`): shared branded UI primitives used in onboarding and settings.
- **Onboarding additions**: \`AchievementsOptInStep\` (opt-in to achievement tracking) and \`AgentsMdPreviewModal\` (preview an agent's AGENTS.md before connecting).
- **Message block parsing** (\`src/lib/messageBlocks.ts\`, \`src/lib/messageMerge.ts\`, \`src/lib/openclaw/clientContext.ts\`): structured decomposition of streamed assistant output into typed blocks for rendering.
- **\`useInputTextController\`**: dedicated hook managing draft text, cursor position, slash-command trigger detection, and paste handling; extracted from \`InputBar\`.
- **\`useTokens\`**: hook for tracking estimated token usage per session.
- **Debug ingest** (\`src/lib/debugIngest.ts\`): dev-only helper for ingesting and replaying raw gateway event logs.
- **Feedback dev bypass token** (\`src/lib/feedback/devBypassToken.ts\`): dev-mode token override for feedback submission without a live cloud account.
- **\`useStreamReveal\`**: hook that produces a progressively revealed string for streaming-text entry animations.
- **Utility modules** (\`src/utils/links.ts\`, \`src/utils/markdownCache.ts\`): safe URL helper and a keyed cache for parsed markdown ASTs to avoid redundant re-parses.
- **New test mocks**: \`expo-network\`, \`file-viewer-context\`, \`reanimated-swipeable\`, \`use-agent-files\`, \`use-agents\`.
- **New test coverage**: \`InteractiveOptionsCard\`, \`StreamingTextRule\`, \`InputBarCard\`, \`useInputTextController\`, \`annotations\`, \`clientContext\`, \`installConventions\`, \`interactive\`, \`messageBlocks\`, \`messageMerge\`, \`messageParsing\`, \`links\`, \`demoIntegration\`.
- **Feedback worker** (\`infra/feedback-worker\`): large expansion of the Cloudflare Worker — enriched ingestion pipeline, structured logging, and updated README.
- **Interactive options protocol doc** (\`docs/interactive-options.md\`): spec for gateway-driven interactive choice messages.

### Changed

- Iterative refactors of the OpenClaw WebSocket **client** and **chat** modules for clearer stream handling, typed events, reconnect behavior, and alignment with gateway semantics.
- **UI polish** across chat (headers, banners, bubbles, lists), onboarding, settings (including server block and meta panels), and theme tokens for consistency with the intended design system.
- **Pairing-required** messaging moved out of a dedicated chat surface into **Settings** (\`PairingRequiredCard\` removed from chat in favor of a settings pairing card).
- **Message list / bubbles**, **slash command palette**, **tool and thinking** cards, **connection banners**, and **input bar** pieces updated for demo mode, i18n, media/audio cues, and layout consistency.
- **Jest** split into **logic** vs **components** projects with shared setup tweaks for faster, clearer test runs.
- **\`useServerConfig\`** and related settings flows expanded for multi-profile editing, sync, and server-row UX; **\`infra/supabase/README\`** updated for the new migrations and functions.
- \`app/settings.tsx\` removed; settings navigation now handled by \`app/settings/_layout.tsx\` and per-screen files under \`app/settings/\`.
- \`MessageBubble\` and \`MessageList\` heavily refactored to render annotation rows, streaming cursor, agent-file viewer trigger, and interactive option cards inline.
- \`InputBar\` extracted input text state into \`useInputTextController\`; action bar, card, header, info row, and rainbow glow cleaned up and aligned with new hook.
- \`OnboardingScreen\` extended with achievements opt-in step and agents-md preview modal.
- \`AboutScreen\` and \`SettingsMetaPanels\` updated to reflect new settings structure and badge/account sections.
- \`SessionRow\` and \`sessionSidebarStyles\` refreshed for badge pip display and visual consistency.
- \`ThemeContext\` and \`theme.ts\` extended with badge tier color tokens and brand-color palette additions.
- \`useChat\` updated for block-based streaming; \`useChatDiskHydration\` and chat cache types extended to persist block structure.
- \`useConnection\` and \`useAutoReconnect\` hardened with cleaner generation tracking and backoff edge cases.
- \`useDraft\` rewritten to delegate text state to \`useInputTextController\`.
- \`DemoOpenClawClient\` updated to emit interactive option events and block-structured messages.
- \`i18n\` (EN + zh-CN) expanded with strings for badges, achievements, annotations, interactive options, conventions, agent files, and new settings screens.
- \`jest.config.js\` updated to include new test suites and mock registrations.
- **Inline reply card** redesigned: single-Q now has a header bar (question prompt or "Reply" fallback), Clear is always visible in the footer (disabled until dirty), Send button matches the main chat input (rounded square, ↑ arrow). Multi-Q dots grouped beside Skip to make pagination context clear; active/answered dots use accent color. \`SegmentedIconPill\` active segment now fills with accent color (applies to Install Mode, Theme Mode, and UI Density selectors).
- **Inline reply primer** (convention v5) compacted ~35%, opens with the explicit framing that interactive cards are the primary way to ask the user questions in ClawBoy.
- **App icon** refreshed to \`icon-grid\` with 3D depth treatment (shine, vignette, gradient-filled glyph, deep drop shadow from \`icon-purple-large\`); constellation updated to NW + S middle + SE (was NW + W middle + SE).
- **Splash screen** now uses a transparent-background variant of the same icon (\`icon-grid-transparent.svg\`) so the grid and glyph composite cleanly over the dark splash \`backgroundColor\` (\`#080B12\`) without any gradient edge clash.
- **Accessibility and localization** pass across chat, settings, onboarding, and shared UI: clearer \`accessibilityLabel\` / role coverage, focus order fixes, and i18n string gaps closed (pre-release audit X6).
- **Voice / TTS**: shared preferences context, audio-session cleanup, and gateway vs device voice heuristics by model; follow-up fixes from voice code review.
- **Onboarding** refactored into \`app/onboarding/steps/*\` and \`components/*\` modules (smaller surfaces, same flow).
- **Slash command palette** split into \`components/input/palette/*\` with hooks extracted for maintainability.
- **Session sidebar**: loading skeleton and error fallback for session list fetch failures.
- **Feedback sheet** split into smaller components and helpers; feedback worker gains Vitest coverage and dependency updates.
- **Repo hygiene (OSS prep)**: reference prototype removed from tracking, audit-driven cleanup of hygiene items (X1).

### Fixed

- **Apple Sign-In button localization** — declared \`CFBundleLocalizations: [en, zh-Hans]\` in \`Info.plist\` so iOS resolves the app's effective UI language correctly. On Simplified Chinese devices the native \`ASAuthorizationAppleIDButton\` now renders "通过 Apple 登录" instead of the English fallback. Side effect: system permission prompts, \`Alert\` default buttons, the share sheet, and other native iOS surfaces also now render in the device language for supported locales.
- **Pinned WebSocket** native module (iOS/Android) follow-ups from native-config audit.
- **Annotations, badges, chat, and common components**: wave-2 / wave-3 audit remediations (correctness, tests, smaller UI fixes).
- **Supabase**: \`fix_purchased_at\` migration for purchase timestamp backfill.
- **Performance and dependencies**: targeted re-render / memo fixes and license-metadata follow-ups (X3 / X4 audits).

### Security

- Gateway tokens, device identity material, Supabase session tokens when used, and chat-cache keys stored via **\`expo-secure-store\`** rather than AsyncStorage; RLS-oriented Supabase schema documented for cloud tables.
- Certificate pinning and explicit flows when a gateway certificate no longer matches a stored pin.
- **WebSocket ingress**: JSON text frames validated with **Zod** before dispatch to protocol handlers; stricter parsing of **auth callback** deep links (X2 security audit).

[Unreleased]: https://github.com/your-org/clawboy-expo/compare/v0.9.0...HEAD
[0.9.0]: https://github.com/your-org/clawboy-expo/releases/tag/v0.9.0
`;
