/**
 * Design tokens for pixel-matching the v0 ClawBoy prototype (`reference/`).
 * Dark defaults use the Prompt 1 palette; light mode mirrors `app/globals.css` :root.
 * VS Code-derived palettes live in `./themes/generated.ts` and are merged below.
 */

import { VSCodePalettes } from './themes/generated';

export const Colors = {
  dark: {
    // Core: true black base + neutral grayscale surfaces.
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#141414',
    cardForeground: '#FFFFFF',
    popover: '#141414',
    popoverForeground: '#FFFFFF',
    // Surfaces: input pills, selector buttons, and cards.
    secondary: '#202020',
    muted: '#202020',
    mutedForeground: '#A8A8A8',
    // Borders & inputs
    border: '#303030',
    input: '#202020',
    ring: '#A855F7',
    // Primary CTA / accent (v0 --primary / purple-500)
    primary: '#A855F7',
    primaryForeground: '#FAFAFA',
    accent: '#A855F7',
    accentForeground: '#FAFAFA',
    // User bubble (v0 .dark --user-bubble)
    userBubble: '#262626',
    userBubbleForeground: '#FAFAFA',
    aiBubble: 'transparent',
    aiBubbleForeground: '#FAFAFA',
    // Sidebar (v0 .dark --sidebar)
    sidebar: '#000000',
    sidebarForeground: '#FAFAFA',
    sidebarPrimary: '#A855F7',
    sidebarPrimaryForeground: '#FAFAFA',
    sidebarAccent: '#202020',
    sidebarAccentForeground: '#FAFAFA',
    sidebarBorder: '#2F2F2F',
    // Semantic
    destructive: '#DC2626',
    destructiveForeground: '#FAFAFA',
    success: '#22C55E',
    successForeground: '#000000',
    warning: '#EAB308',
    warningForeground: '#000000',
    thinking: '#A855F7',
    thinkingForeground: '#FAFAFA',
    tool: '#A855F7',
    toolForeground: '#FAFAFA',
    // Inline warning text — readable on the screen background (not on a warning button)
    warningText: '#EAB308',
    // Rainbow / gradient accents (input glow, v0 globals)
    accentViolet: '#8B5CF6',
    accentIndigo: '#6366F1',
    accentBlue: '#3B82F6',
    shimmerBase: '#8C8C8C',
    shimmerHighlight: '#F2F2F2',
  },
  darkBlue: {
    // Core: deep navy base (original Prompt 1 palette, oklch 0.145 background).
    background: '#0F1219',
    foreground: '#F5F5F5',
    card: '#151A24',
    cardForeground: '#F5F5F5',
    popover: '#151A24',
    popoverForeground: '#F5F5F5',
    // Surfaces: slightly elevated blue-tinted panels.
    secondary: '#1A1F2E',
    muted: '#1A1F2E',
    mutedForeground: '#8B8B8B',
    // Borders — bumped slightly lighter than surface so edges read on navy.
    border: '#222A3A',
    input: '#1A1F2E',
    ring: '#A855F7',
    // Primary CTA / accent
    primary: '#A855F7',
    primaryForeground: '#FAFAFA',
    accent: '#A855F7',
    accentForeground: '#FAFAFA',
    // User bubble
    userBubble: '#333333',
    userBubbleForeground: '#FAFAFA',
    aiBubble: 'transparent',
    aiBubbleForeground: '#F5F5F5',
    // Sidebar
    sidebar: '#0A0E16',
    sidebarForeground: '#FAFAFA',
    sidebarPrimary: '#A855F7',
    sidebarPrimaryForeground: '#FAFAFA',
    sidebarAccent: '#1A1F2E',
    sidebarAccentForeground: '#FAFAFA',
    sidebarBorder: '#222A3A',
    // Semantic
    destructive: '#DC2626',
    destructiveForeground: '#FAFAFA',
    success: '#22C55E',
    successForeground: '#000000',
    warning: '#EAB308',
    warningForeground: '#000000',
    thinking: '#A855F7',
    thinkingForeground: '#FAFAFA',
    tool: '#A855F7',
    toolForeground: '#FAFAFA',
    warningText: '#EAB308',
    // Rainbow / gradient accents (identical to dark — glow looks great on navy)
    accentViolet: '#8B5CF6',
    accentIndigo: '#6366F1',
    accentBlue: '#3B82F6',
    shimmerBase: '#8C8C8C',
    shimmerHighlight: '#F2F2F2',
  },
  light: {
    background: '#FFFFFF',
    foreground: '#0A0A0A',
    card: '#FFFFFF',
    cardForeground: '#0A0A0A',
    popover: '#FFFFFF',
    popoverForeground: '#0A0A0A',
    secondary: '#F4F4F5',
    muted: '#E4E4E7',
    mutedForeground: '#71717A',
    border: '#E4E4E7',
    input: '#F4F4F5',
    ring: '#A855F7',
    primary: '#A855F7',
    primaryForeground: '#FAFAFA',
    accent: '#A855F7',
    accentForeground: '#FAFAFA',
    userBubble: '#F4F4F5',
    userBubbleForeground: '#0A0A0A',
    aiBubble: 'transparent',
    aiBubbleForeground: '#0A0A0A',
    sidebar: '#FAFAFA',
    sidebarForeground: '#0A0A0A',
    sidebarPrimary: '#A855F7',
    sidebarPrimaryForeground: '#FAFAFA',
    sidebarAccent: '#F4F4F5',
    sidebarAccentForeground: '#0A0A0A',
    sidebarBorder: '#E4E4E7',
    destructive: '#DC2626',
    destructiveForeground: '#FAFAFA',
    success: '#22C55E',
    successForeground: '#FFFFFF',
    warning: '#EAB308',
    warningForeground: '#FFFFFF',
    thinking: '#A855F7',
    thinkingForeground: '#FAFAFA',
    tool: '#A855F7',
    toolForeground: '#FAFAFA',
    // Inline warning text — dark amber (readable on light backgrounds)
    warningText: '#92400E',
    accentViolet: '#8B5CF6',
    accentIndigo: '#6366F1',
    accentBlue: '#3B82F6',
    shimmerBase: '#8C8C8C',
    shimmerHighlight: '#F2F2F2',
  },
  ...VSCodePalettes,

  /** Founders Silver+ — warm ember / amber dark palette. */
  foundersAmber: {
    background: '#0D0900',
    foreground: '#F5ECD7',
    card: '#150E00',
    cardForeground: '#F5ECD7',
    popover: '#150E00',
    popoverForeground: '#F5ECD7',
    secondary: '#1E1500',
    muted: '#1E1500',
    mutedForeground: '#9B8060',
    border: '#2E1F00',
    input: '#1E1500',
    ring: '#CD7F32',
    primary: '#CD7F32',
    primaryForeground: '#FAFAFA',
    accent: '#CD7F32',
    accentForeground: '#FAFAFA',
    userBubble: '#241900',
    userBubbleForeground: '#F5ECD7',
    aiBubble: 'transparent',
    aiBubbleForeground: '#F5ECD7',
    sidebar: '#080500',
    sidebarForeground: '#F5ECD7',
    sidebarPrimary: '#CD7F32',
    sidebarPrimaryForeground: '#FAFAFA',
    sidebarAccent: '#1E1500',
    sidebarAccentForeground: '#F5ECD7',
    sidebarBorder: '#2E1F00',
    destructive: '#DC2626',
    destructiveForeground: '#FAFAFA',
    success: '#22C55E',
    successForeground: '#000000',
    warning: '#EAB308',
    warningForeground: '#000000',
    thinking: '#CD7F32',
    thinkingForeground: '#FAFAFA',
    tool: '#CD7F32',
    toolForeground: '#FAFAFA',
    warningText: '#EAB308',
    accentViolet: '#CD7F32',
    accentIndigo: '#B8860B',
    accentBlue: '#D2691E',
    shimmerBase: '#8C8C8C',
    shimmerHighlight: '#F2F2F2',
  },

  /** Founders Gold exclusive — northern lights aurora palette. */
  foundersAurora: {
    background: '#020B0E',
    foreground: '#D6F5F0',
    card: '#041217',
    cardForeground: '#D6F5F0',
    popover: '#041217',
    popoverForeground: '#D6F5F0',
    secondary: '#071E25',
    muted: '#071E25',
    mutedForeground: '#608090',
    border: '#0D2E3A',
    input: '#071E25',
    ring: '#00FFD0',
    primary: '#00C8A0',
    primaryForeground: '#020B0E',
    accent: '#00C8A0',
    accentForeground: '#020B0E',
    userBubble: '#092030',
    userBubbleForeground: '#D6F5F0',
    aiBubble: 'transparent',
    aiBubbleForeground: '#D6F5F0',
    sidebar: '#010809',
    sidebarForeground: '#D6F5F0',
    sidebarPrimary: '#00C8A0',
    sidebarPrimaryForeground: '#020B0E',
    sidebarAccent: '#071E25',
    sidebarAccentForeground: '#D6F5F0',
    sidebarBorder: '#0D2E3A',
    destructive: '#FF4D6D',
    destructiveForeground: '#FAFAFA',
    success: '#00E5A0',
    successForeground: '#020B0E',
    warning: '#FFD166',
    warningForeground: '#020B0E',
    thinking: '#00C8A0',
    thinkingForeground: '#020B0E',
    tool: '#6BC5FF',
    toolForeground: '#020B0E',
    warningText: '#FFD166',
    accentViolet: '#A855F7',
    accentIndigo: '#6366F1',
    accentBlue: '#00C8A0',
    shimmerBase: '#608090',
    shimmerHighlight: '#D6F5F0',
  },

  /** ClawBoy brand dark — cowgirl logo palette (blue claws · pink hat band · warm tan hat). */
  cowgirlDark: {
    background: '#0B0F18',
    foreground: '#F4F6FA',
    card: '#121826',
    cardForeground: '#F4F6FA',
    popover: '#121826',
    popoverForeground: '#F4F6FA',
    secondary: '#1A2030',
    muted: '#1A2030',
    mutedForeground: '#8B9AB3',
    border: '#22293A',
    input: '#1A2030',
    ring: '#4DA3F0',
    primary: '#4DA3F0',
    primaryForeground: '#08111E',
    accent: '#F0A2B0',
    accentForeground: '#1A0A10',
    userBubble: '#1F2738',
    userBubbleForeground: '#F4F6FA',
    aiBubble: 'transparent',
    aiBubbleForeground: '#F4F6FA',
    sidebar: '#080B12',
    sidebarForeground: '#F4F6FA',
    sidebarPrimary: '#4DA3F0',
    sidebarPrimaryForeground: '#08111E',
    sidebarAccent: '#1A2030',
    sidebarAccentForeground: '#F4F6FA',
    sidebarBorder: '#22293A',
    destructive: '#E5526B',
    destructiveForeground: '#FAFAFA',
    success: '#3FBF7F',
    successForeground: '#08111E',
    warning: '#E5BD6F',
    warningForeground: '#1A1208',
    thinking: '#4DA3F0',
    thinkingForeground: '#08111E',
    tool: '#F0A2B0',
    toolForeground: '#1A0A10',
    warningText: '#E5BD6F',
    // Rainbow-glow: pink → yellow-tan → blue (the three logo accent colours)
    accentViolet: '#F0A2B0',
    accentIndigo: '#F4C842',
    accentBlue: '#4DA3F0',
    shimmerBase: '#8B9AB3',
    shimmerHighlight: '#F4F6FA',
  },

  /** ClawBoy brand light — cowgirl logo palette on a warm cream base. */
  cowgirlLight: {
    background: '#FFFAF1',
    foreground: '#16202E',
    card: '#FFFFFF',
    cardForeground: '#16202E',
    popover: '#FFFFFF',
    popoverForeground: '#16202E',
    secondary: '#FCEFD8',
    muted: '#F2E5CC',
    mutedForeground: '#7A6A52',
    border: '#E8DAC0',
    input: '#FCEFD8',
    ring: '#3B8DD9',
    primary: '#3B8DD9',
    primaryForeground: '#FFFFFF',
    accent: '#E0738E',
    accentForeground: '#FFFFFF',
    userBubble: '#FCEFD8',
    userBubbleForeground: '#16202E',
    aiBubble: 'transparent',
    aiBubbleForeground: '#16202E',
    sidebar: '#FFF6E6',
    sidebarForeground: '#16202E',
    sidebarPrimary: '#3B8DD9',
    sidebarPrimaryForeground: '#FFFFFF',
    sidebarAccent: '#FCEFD8',
    sidebarAccentForeground: '#16202E',
    sidebarBorder: '#E8DAC0',
    destructive: '#D03A53',
    destructiveForeground: '#FFFFFF',
    success: '#2E9E64',
    successForeground: '#FFFFFF',
    warning: '#D9A93C',
    warningForeground: '#FFFFFF',
    thinking: '#3B8DD9',
    thinkingForeground: '#FFFFFF',
    tool: '#E0738E',
    toolForeground: '#FFFFFF',
    warningText: '#7A4D08',
    // Rainbow-glow: pink → amber → blue on warm cream
    accentViolet: '#E0738E',
    accentIndigo: '#D9A93C',
    accentBlue: '#3B8DD9',
    shimmerBase: '#7A6A52',
    shimmerHighlight: '#16202E',
  },
} as const;

/** v0 --radius: 0.75rem → 12px */
export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  '2xl': 24,
  '3xl': 32,
  '4xl': 40,
} as const;

export const BorderRadius = {
  sm: 8, // calc(12px - 4px) — v0 radius-sm
  md: 10, // calc(12px - 2px)
  lg: 12, // --radius
  xl: 16, // calc(12px + 4px)
  '2xl': 16, // rounded-2xl message bubbles
  full: 9999,
} as const;

export const FontSize = {
  xs: 12,
  sm: 14,
  base: 15,
  md: 16,
  lg: 18,
  xl: 20,
  '2xl': 24,
} as const;

export const FontWeight = {
  normal: '400' as const,
  medium: '500' as const,
  semibold: '600' as const,
  bold: '700' as const,
} as const;
